const common = {
  brands: { olivia:'Olivia AI', mail:'Olivia One Mail', control:'Olivia Control Center', crm:'O7 PulseCRM', erp:'O7 ERP', transport:'O7 Transport OS' },
  mailItems:['Operations — Payment approval','Sales — Action required','Legal — Contract review','Customer Success — Follow-up'],
  controlModules:['AI Agents','Conversations','Email','CRM','ERP','Operations','Automations','Alerts','Revenue','System Status','Analytics'],
  crmModules:['Leads','Opportunities','Pipeline','Tasks','Activities','Communication history','Documents','Automations'],
  crmAi:['Lead Score','Conversation Summary','Next Best Action','Generate Follow-up','Pipeline Prediction','Smart Search'],
  erpModules:['Finance','Sales','Purchasing','Projects','Inventory','HR','Documents','Operations','Analytics'],
  transportModules:['Operations','Dispatch','Drivers','Fleet','Directions','Finance','CRM','WhatsApp','AI assistance','Analytics'],
  infraModules:['Cloud','Hosting','Mail Infrastructure','Managed Services','Security','DevOps','Networking','Business Continuity']
};

export const premium = {
  en:{...common,
    ui:{inbox:'Inbox',priority:'Priority',assigned:'Assigned',sent:'Sent',archive:'Archive',activeAgents:'ACTIVE AGENTS',today:'+3 TODAY',pipeline:'PIPELINE',automations:'AUTOMATIONS',systemOk:'99.8% OK'},
    nav:{group:'Group',technology:'Technology',olivia:'Olivia AI',platforms:'Platforms',units:'Business Units',global:'Global Presence',contact:'Contact',menu:'Menu',close:'Close'},
    hero:{eyebrow:'INTERNATIONAL TECHNOLOGY GROUP',title:['WE BUILD.','WE OPERATE.','WE SCALE.'],text:'O7 Digital Group is an international technology group building artificial intelligence, enterprise software, digital infrastructure and operating platforms for organizations across North America, Latin America and Europe.',regions:'UNITED STATES · CANADA · MEXICO · EUROPE',domains:'AI · SOFTWARE · INFRASTRUCTURE · OPERATIONS',primary:'Explore the ecosystem',secondary:'Global presence',networkAria:'O7 Group network connecting four international hubs',core:'GROUP CORE',hubs:[{code:'US',name:'UNITED STATES',meta:'GROUP STRATEGY · AMERICAS'},{code:'CA',name:'CANADA',meta:'QUÉBEC · CANADIAN OPERATIONS'},{code:'MX',name:'MEXICO',meta:'LATAM · TECHNOLOGY OPERATIONS'},{code:'EU',name:'EUROPE',meta:'FRANCE · EUROPEAN OPERATIONS'}]},
    overview:{index:'GROUP OVERVIEW',kicker:'ONE GROUP. ONE CONNECTED TECHNOLOGY VISION.',title:['Enterprise technology,','built to operate.'],text:'O7 Digital Group builds and operates a connected ecosystem spanning intelligence, communications, CRM, ERP, vertical operating systems, infrastructure and consulting.',quote:'A United States-led international technology group with operations across Canada, Mexico and Europe.'},
    ecosystem:{index:'O7 TECHNOLOGY ECOSYSTEM',title:'One intelligence layer. One connected business ecosystem.',core:'INTELLIGENCE CORE',business:'BUSINESS LAYER',vertical:'VERTICAL SYSTEMS',agents:'AI AGENTS'},
    olivia:{index:'OLIVIA AI',claim:'The intelligence layer of the O7 ecosystem.',p1:'Olivia AI is the intelligence core of the O7 ecosystem. An artificial intelligence platform designed to converse, understand business information, automate processes and operate connected to an organization’s systems.',p2:'Olivia works across CRM, email, operations, knowledge bases and vertical platforms as an assistant, agent or enterprise intelligence layer.',capabilities:['Conversational AI','Business Agents','Workflow Automation','Knowledge Retrieval','Lead Qualification','Customer Support','Multilingual Communication','Operational Intelligence','CRM Intelligence','Email Intelligence'],ask:'ASK OLIVIA',question:'What requires my attention across the business today?',answer:'I found 12 priority actions across sales, operations and customer communications.'},
    mail:{index:'COMMUNICATION INTELLIGENCE',claim:'Email becomes an intelligent workspace.',text:'Olivia One Mail centralizes business communications and adds an AI layer able to classify, summarize, search, prioritize and assist with message management.',inbox:'INBOX',ask:'ASK OLIVIA',question:'What requires my attention?',answer:'3 conversations require action today.',features:['Summaries','Priority detection','Semantic search','Suggested replies','Follow-up','CRM synchronization','Multilingual assistance']},
    control:{index:'ENTERPRISE COMMAND',claim:'One command center for the entire business.',text:'A unified operating view connecting intelligence, communications, commercial activity and business systems.',ask:'ASK OLIVIA',question:'Show me opportunities requiring action in Mexico this week.',answer:'3 workflows need action',results:['Sales · Proposal review','Customer Success · Follow-up overdue','Legal · Contract approval','Finance · Payment pending']},
    crm:{index:'BUSINESS PLATFORM',claim:'CRM built around action, not administration.',text:'Leads, opportunities, customers, activities, documents, communications and automations in one platform connected to Olivia AI.',powered:'Powered by Olivia AI'},
    erp:{index:'BUSINESS PLATFORM',claim:'Enterprise operations. Connected by intelligence.',text:'A modular operating platform linking finance, sales, purchasing, projects, inventory, people and analytics through Olivia AI.',powered:'Powered by Olivia AI'},
    vertical:{index:'VERTICAL TECHNOLOGY',title:'Industry-specific operating systems built on the O7 technology ecosystem.',claim:'Intelligent operations for transportation companies.',text:'A connected operating environment for transport activity, from dispatch and fleet to finance, communications and analytics.',powered:'Powered by Olivia One'},
    consulting:{label:'OPERATING COMPANY',text:'Digital strategy, software engineering, AI implementation, SEO, platforms and enterprise transformation.',cta:'Visit O7 Digital Consulting'},
    infra:{label:'BUSINESS UNIT',title:'Infrastructure & Managed Technology',claim:'The operational foundation behind the ecosystem.',text:'O7 operates the cloud, security, networks and managed environments on which its products and enterprise systems run.'},
    presence:{index:'GLOBAL PRESENCE',title:'Technology built across borders. Designed to scale globally.',usa:['UNITED STATES','Group Strategy & Americas'],canada:['CANADA — QUÉBEC','Canadian Operations','9517-6806 Québec Inc.','1030, Avenue Muguette · Saint-Élie-de-Caxton, QC G0X 2N0 · Canada','+1 (819) 996-1177'],mexico:['MEXICO','LATAM Operations & Technology'],europe:['FRANCE / EUROPE','European Operations & Consulting']},
    partners:{index:'PARTNERSHIPS / ENTERPRISE',title:'Built for long-term enterprise collaboration.',text:'Technology alliances, strategic partnerships and complex international programs.'}
  },
  es:{...common,
    ui:{inbox:'Entrada',priority:'Prioridad',assigned:'Asignados',sent:'Enviados',archive:'Archivo',activeAgents:'AGENTES ACTIVOS',today:'+3 HOY',pipeline:'PIPELINE',automations:'AUTOMATIZACIONES',systemOk:'99.8% OK'},
    nav:{group:'Grupo',technology:'Tecnología',olivia:'Olivia AI',platforms:'Plataformas',units:'Unidades de negocio',global:'Presencia global',contact:'Contacto',menu:'Menú',close:'Cerrar'},
    hero:{eyebrow:'GRUPO TECNOLÓGICO INTERNACIONAL',title:['CONSTRUIMOS.','OPERAMOS.','ESCALAMOS.'],text:'O7 Digital Group es un grupo tecnológico internacional que desarrolla inteligencia artificial, software empresarial, infraestructura digital y plataformas operativas para organizaciones en América del Norte, Latinoamérica y Europa.',regions:'ESTADOS UNIDOS · CANADÁ · MÉXICO · EUROPA',domains:'IA · SOFTWARE · INFRAESTRUCTURA · OPERACIONES',primary:'Explorar el ecosistema',secondary:'Presencia global',networkAria:'Red O7 Group conectando cuatro polos internacionales',core:'NÚCLEO DEL GRUPO',hubs:[{code:'US',name:'ESTADOS UNIDOS',meta:'ESTRATEGIA DEL GRUPO · AMÉRICAS'},{code:'CA',name:'CANADÁ',meta:'QUÉBEC · OPERACIONES CANADIENSES'},{code:'MX',name:'MÉXICO',meta:'LATAM · OPERACIONES TECNOLÓGICAS'},{code:'EU',name:'EUROPA',meta:'FRANCIA · OPERACIONES EUROPEAS'}]},
    overview:{index:'VISIÓN DEL GRUPO',kicker:'UN GRUPO. UNA VISIÓN TECNOLÓGICA CONECTADA.',title:['Tecnología empresarial,','creada para operar.'],text:'O7 Digital Group construye y opera un ecosistema conectado de inteligencia, comunicaciones, CRM, ERP, sistemas operativos verticales, infraestructura y consultoría.',quote:'Grupo tecnológico internacional orientado desde Estados Unidos, con operaciones en Canadá, México y Europa.'},
    ecosystem:{index:'ECOSISTEMA TECNOLÓGICO O7',title:'Una capa de inteligencia. Un ecosistema empresarial conectado.',core:'NÚCLEO DE INTELIGENCIA',business:'CAPA EMPRESARIAL',vertical:'SISTEMAS VERTICALES',agents:'AGENTES IA'},
    olivia:{index:'OLIVIA AI',claim:'El núcleo de inteligencia del ecosistema O7.',p1:'Olivia AI es el núcleo de inteligencia del ecosistema O7. Una plataforma de inteligencia artificial diseñada para conversar, comprender información empresarial, automatizar procesos y operar conectada con los sistemas de una organización.',p2:'Olivia puede trabajar sobre CRM, correo electrónico, operaciones, bases de conocimiento y plataformas verticales, actuando como asistente, agente o capa de inteligencia empresarial.',capabilities:['IA conversacional','Agentes empresariales','Automatización de workflows','Recuperación de conocimiento','Calificación de leads','Atención al cliente','Comunicación multilingüe','Inteligencia operativa','Inteligencia CRM','Inteligencia de email'],ask:'PREGUNTA A OLIVIA',question:'¿Qué requiere mi atención hoy en toda la empresa?',answer:'Encontré 12 acciones prioritarias en ventas, operaciones y comunicaciones con clientes.'},
    mail:{index:'INTELIGENCIA DE COMUNICACIÓN',claim:'El correo electrónico se convierte en un espacio de trabajo inteligente.',text:'Olivia One Mail centraliza las comunicaciones empresariales y añade una capa de inteligencia artificial capaz de clasificar, resumir, buscar, priorizar y asistir en la gestión de mensajes.',inbox:'BANDEJA DE ENTRADA',ask:'PREGUNTA A OLIVIA',question:'¿Qué requiere mi atención?',answer:'3 conversaciones requieren acción hoy.',features:['Resúmenes','Detección de prioridad','Búsqueda semántica','Respuestas sugeridas','Seguimiento','Sincronización CRM','Asistencia multilingüe']},
    control:{index:'COMANDO EMPRESARIAL',claim:'Un centro de control para toda la empresa.',text:'Una visión operativa unificada que conecta inteligencia, comunicaciones, actividad comercial y sistemas empresariales.',ask:'PREGUNTA A OLIVIA',question:'Muéstrame las oportunidades que requieren acción en México esta semana.',answer:'3 flujos requieren acción',results:['Ventas · Revisar propuesta','Customer Success · Seguimiento pendiente','Legal · Aprobar contrato','Finanzas · Pago pendiente']},
    crm:{index:'PLATAFORMA EMPRESARIAL',claim:'Un CRM diseñado para actuar, no para administrar burocracia.',text:'Leads, oportunidades, clientes, actividades, documentos, comunicaciones y automatizaciones reunidos en una única plataforma conectada con Olivia AI.',powered:'Impulsado por Olivia AI'},
    erp:{index:'PLATAFORMA EMPRESARIAL',claim:'Operaciones empresariales conectadas por inteligencia.',text:'Una plataforma modular que conecta finanzas, ventas, compras, proyectos, inventario, personas y analítica mediante Olivia AI.',powered:'Impulsado por Olivia AI'},
    vertical:{index:'TECNOLOGÍA VERTICAL',title:'Sistemas operativos específicos para cada industria construidos sobre el ecosistema tecnológico O7.',claim:'Operaciones inteligentes para empresas de transporte.',text:'Un entorno operativo conectado para el transporte, desde despacho y flota hasta finanzas, comunicaciones y analítica.',powered:'Impulsado por Olivia One'},
    consulting:{label:'EMPRESA OPERATIVA',text:'Estrategia digital, ingeniería de software, implementación de IA, SEO, plataformas y transformación empresarial.',cta:'Visitar O7 Digital Consulting'},
    infra:{label:'UNIDAD DE NEGOCIO',title:'Infraestructura y Tecnología Gestionada',claim:'La base operativa detrás del ecosistema.',text:'O7 opera el cloud, la seguridad, las redes y los entornos gestionados donde funcionan sus productos y sistemas empresariales.'},
    presence:{index:'PRESENCIA GLOBAL',title:'Tecnología construida sin fronteras. Diseñada para escalar globalmente.',usa:['ESTADOS UNIDOS','Estrategia del Grupo y Américas'],canada:['CANADÁ — QUÉBEC','Operaciones canadienses','9517-6806 Québec Inc.','1030, Avenue Muguette · Saint-Élie-de-Caxton, QC G0X 2N0 · Canadá','+1 (819) 996-1177'],mexico:['MÉXICO','Operaciones LATAM y Tecnología'],europe:['FRANCIA / EUROPA','Operaciones europeas y Consultoría']},
    partners:{index:'ALIANZAS / EMPRESA',title:'Diseñado para colaboraciones empresariales duraderas.',text:'Alianzas tecnológicas, asociaciones estratégicas y programas internacionales complejos.'}
  }
};

const variants = {
  fr:{group:'Groupe',technology:'Technologie',platforms:'Plateformes',units:'Business Units',global:'Présence mondiale',contact:'Contact',eyebrow:'GROUPE TECHNOLOGIQUE INTERNATIONAL',title:['NOUS CRÉONS.','NOUS OPÉRONS.','NOUS ACCÉLÉRONS.'],primary:'Explorer l’écosystème',secondary:'Présence mondiale'},
  de:{group:'Gruppe',technology:'Technologie',platforms:'Plattformen',units:'Geschäftseinheiten',global:'Globale Präsenz',contact:'Kontakt',eyebrow:'INTERNATIONALE TECHNOLOGIEGRUPPE',title:['WIR ENTWICKELN.','WIR BETREIBEN.','WIR SKALIEREN.'],primary:'Ökosystem entdecken',secondary:'Globale Präsenz'},
  it:{group:'Gruppo',technology:'Tecnologia',platforms:'Piattaforme',units:'Business Unit',global:'Presenza globale',contact:'Contatti',eyebrow:'GRUPPO TECNOLOGICO INTERNAZIONALE',title:['COSTRUIAMO.','OPERIAMO.','CRESCIAMO.'],primary:'Scopri l’ecosistema',secondary:'Presenza globale'},
  pt:{group:'Grupo',technology:'Tecnologia',platforms:'Plataformas',units:'Unidades de negócio',global:'Presença global',contact:'Contacto',eyebrow:'GRUPO TECNOLÓGICO INTERNACIONAL',title:['CONSTRUÍMOS.','OPERAMOS.','ESCALAMOS.'],primary:'Explorar o ecossistema',secondary:'Presença global'}
};
for (const [code, v] of Object.entries(variants)) premium[code] = { ...premium.en, nav:{...premium.en.nav,...v,olivia:'Olivia AI'}, hero:{...premium.en.hero,eyebrow:v.eyebrow,title:v.title,primary:v.primary,secondary:v.secondary} };

Object.assign(premium.fr, {
  ui:{...premium.en.ui,inbox:'Boîte de réception',priority:'Priorité',assigned:'Assignés',sent:'Envoyés',archive:'Archives',activeAgents:'AGENTS ACTIFS',today:'+3 AUJOURD’HUI',automations:'AUTOMATISATIONS'},
  hero:{...premium.fr.hero,text:'O7 Digital Group est un groupe technologique international qui développe de l’intelligence artificielle, des logiciels d’entreprise, des infrastructures numériques et des plateformes opérationnelles pour les organisations en Amérique du Nord, en Amérique latine et en Europe.',regions:'ÉTATS-UNIS · CANADA · MEXIQUE · EUROPE',domains:'IA · LOGICIELS · INFRASTRUCTURE · OPÉRATIONS'},
  overview:{index:'VUE D’ENSEMBLE DU GROUPE',kicker:'UN GROUPE. UNE VISION TECHNOLOGIQUE CONNECTÉE.',title:['La technologie d’entreprise,','conçue pour opérer.'],text:'O7 Digital Group construit et opère un écosystème connecté couvrant intelligence, communications, CRM, ERP, systèmes verticaux, infrastructure et conseil.',quote:'Un groupe technologique international orienté depuis les États-Unis, avec des opérations au Canada, au Mexique et en Europe.'},
  ecosystem:{...premium.en.ecosystem,index:'ÉCOSYSTÈME TECHNOLOGIQUE O7',title:'Une couche d’intelligence. Un écosystème d’entreprise connecté.',core:'CŒUR D’INTELLIGENCE',business:'COUCHE MÉTIER',vertical:'SYSTÈMES VERTICAUX',agents:'AGENTS IA'},
  olivia:{...premium.en.olivia,claim:'La couche d’intelligence de l’écosystème O7.',p1:'Olivia AI est le cœur intelligent de l’écosystème O7, conçu pour dialoguer, comprendre les informations métier, automatiser les processus et se connecter aux systèmes de l’organisation.',p2:'Olivia agit sur le CRM, les e-mails, les opérations, les bases de connaissances et les plateformes verticales comme assistante, agent ou couche d’intelligence d’entreprise.',ask:'DEMANDER À OLIVIA'},
  mail:{...premium.en.mail,claim:'L’e-mail devient un espace de travail intelligent.',text:'Olivia One Mail centralise les communications et ajoute une intelligence capable de classer, résumer, rechercher, prioriser et assister la gestion des messages.',inbox:'BOÎTE DE RÉCEPTION',ask:'DEMANDER À OLIVIA'},
  control:{...premium.en.control,claim:'Un centre de commande pour toute l’entreprise.',text:'Une vision opérationnelle unifiée reliant intelligence, communications, activité commerciale et systèmes métier.',ask:'DEMANDER À OLIVIA'},
  crm:{...premium.en.crm,claim:'Un CRM centré sur l’action, pas l’administration.',text:'Prospects, opportunités, clients, activités, documents, communications et automatisations dans une plateforme connectée à Olivia AI.',powered:'Propulsé par Olivia AI'},
  erp:{...premium.en.erp,claim:'Les opérations d’entreprise connectées par l’intelligence.',text:'Une plateforme modulaire reliant finance, ventes, achats, projets, stocks, équipes et analytique grâce à Olivia AI.',powered:'Propulsé par Olivia AI'},
  vertical:{...premium.en.vertical,index:'TECHNOLOGIE VERTICALE',title:'Des systèmes opérationnels sectoriels construits sur l’écosystème O7.',claim:'Des opérations intelligentes pour les entreprises de transport.',powered:'Propulsé par Olivia One'},
  consulting:{label:'SOCIÉTÉ OPÉRATIONNELLE',text:'Stratégie numérique, ingénierie logicielle, mise en œuvre de l’IA, SEO, plateformes et transformation d’entreprise.',cta:'Visiter O7 Digital Consulting'},
  infra:{...premium.en.infra,label:'UNITÉ MÉTIER',title:'Infrastructure & Technologie Managée',claim:'La fondation opérationnelle de l’écosystème.'},
  presence:{...premium.en.presence,index:'PRÉSENCE MONDIALE',title:'Une technologie construite au-delà des frontières. Conçue pour évoluer mondialement.'},
  partners:{index:'PARTENARIATS / ENTREPRISE',title:'Conçu pour des collaborations durables.',text:'Alliances technologiques, partenariats stratégiques et programmes internationaux complexes.'}
});

for (const code of ['de','it','pt']) {
  const v = variants[code];
  premium[code] = {
    ...premium[code],
    hero:{...premium[code].hero,regions:code==='de'?'USA · KANADA · MEXIKO · EUROPA':code==='it'?'STATI UNITI · CANADA · MESSICO · EUROPA':'ESTADOS UNIDOS · CANADÁ · MÉXICO · EUROPA'},
    overview:{...premium.en.overview,index:code==='de'?'GRUPPENÜBERSICHT':code==='it'?'PANORAMICA DEL GRUPPO':'VISÃO DO GRUPO'},
    ecosystem:{...premium.en.ecosystem,index:code==='de'?'O7 TECHNOLOGIEÖKOSYSTEM':code==='it'?'ECOSISTEMA TECNOLOGICO O7':'ECOSSISTEMA TECNOLÓGICO O7'},
    presence:{...premium.en.presence,index:v.global.toUpperCase()},
    consulting:{...premium.en.consulting,label:code==='de'?'OPERATIVES UNTERNEHMEN':code==='it'?'SOCIETÀ OPERATIVA':'EMPRESA OPERACIONAL'}
  };
}
